### ISSUE TITLE
ios sdk plist files missing BundleIdentifier and Version codes

### ISSUE THREAD

**Issue by benconnito** [apptentive/apptentive-cordova#10]
the ios sdk resource.bundle Info.plist is missing a bundle identifier and version (regular and short) numbers.

When you try to submit an archive ITC complains that the bundle identifier contains invalid chars and that it is missing version numbers. Deleting the Info.plist and the .momd VersionInfo.plist files resolves this. (but breaks the sdk)

See:
https://github.com/apptentive/apptentive-ios/issues/163

**Comment by jfspencer** [comment]
+1

**Comment by CestLou** [comment]
thanks for bringing this to our attention. 

as you saw, we addressed and fixed this related issue on the SDK. there is an open pull request to require apptentive 2.0.5 in this project, to fix this issue. stay tuned.

**Comment by CestLou** [comment]
issue should now be resolved. please pull down our latest release.
