### ISSUE TITLE
How to push Feedback screen instead of presenting it?

### ISSUE THREAD

**Issue by parvez-inheritx** [apptentive/apptentive-cordova#15]
Currently when the user tap feedback button we have used the readymade code provided by Apptentive classes  which is given below:-

[[ATConnect sharedConnection] presentMessageCenterFromViewController:self];

But using this code, the ATMessageCenterViewController gets presented, and based on our application requirement we have to push this, instead of presenting it and additionally we have to customize this screen to match the look and feel of the application.

So is there any predefined way to customize Feedback screen(ATMessageCenterViewController) and push it instead of presenting it ?

**Comment by frankus** [comment]
Sorry for the inexcusably long delay in replying. We do not have a way to present the Message Center controller in a push fashion, unfortunately.
