### ISSUE TITLE
Plugins fails to compile for Android SDK 23

### ISSUE THREAD

**Issue by terrorhawks** [apptentive/apptentive-cordova#18]
```
/android/sdk/comm/ApptentiveClient.java:15: error: package org.apache.http does not exist
import org.apache.http.Header;``
```

HttpClient is not supported any more in sdk 23. You have to use URLConnection.

**Comment by appplumbr** [comment]
+ 1

**Comment by barry-li** [comment]
Make sure you are using our latest Cordova plugin. We have switched away from apache since last Oct. FYI, the source can be seen at our public git:
https://github.com/apptentive/apptentive-android/blob/master/apptentive/src/com/apptentive/android/sdk/comm/ApptentiveClient.java
