### ISSUE TITLE
Android build (android api v23) fails at (Apptenti veBridge.java:232: error: cannot find symbol) with latest clone 

### ISSUE THREAD

**Issue by ghost** [apptentive/apptentive-cordova#20]
It worked day before and stopped with this (commit dfd70144b7736979a9b636fe305d59d4e1661080)

Error log:

\cordova\ApptentiveBridge.java:9: error: cannot find symbol
import com.apptentive.android.sdk.Log;
                                 ^
  symbol:   class Log
  location: package com.apptentive.android.sdk
android\src\com\apptentive\cordova\Apptenti
veBridge.java:64: error: cannot find symbol
                Log.v("Executing action: %s", action);
                ^
  symbol:   variable Log
  location: class ApptentiveBridge
\android\src\com\apptentive\cordova\Apptenti
veBridge.java:232: error: cannot find symbol
                        Log.i("Adding message listener.");
                        ^
  symbol:   variable Log
  location: class ApptentiveBridge
android\src\com\apptentive\cordova\Apptenti
veBridge.java:235: error: cannot find symbol
                                        Log.i("Unread messages: %d", unreadMessa
ges);
                                        ^
  symbol: variable Log
android\src\com\apptentive\cordova\Apptenti
veBridge.java:257: error: cannot find symbol
                Log.w("Unhandled action in ApptentiveBridge: %s", action);

**Comment by barry-li** [comment]
Thanks for reporting this issue. It has been updated with the correct log class name

**Comment by appplumbr** [comment]
@barry-li Welcome
