### ISSUE TITLE
Look and feel customization?

### ISSUE THREAD

**Issue by cgs** [apptentive/apptentive-cordova#28]
Is it possible to customize the UI? Looks like for Android [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) would do the trick. For iOS I'm guessing I'd need to fork the plugin?

**Comment by cgs** [comment]
For customizing Android:

create platforms/android/res/values/apptentive.xml

    <?xml version='1.0' encoding='utf-8'?>
    <resources>
      <style name="ApptentiveThemeOverride">
        <item name="colorPrimary">#E6E6E6</item>
        <item name="colorPrimaryDark">#FFFFFF</item>
      </style>
    </resources>

**Comment by frankus** [comment]
Sorry for missing this. We do have a solution in place now for iOS using a style plist, which you can find here: 
https://learn.apptentive.com/knowledge-base/interface-customization-ios/#initializing-from-a-property-list

The React Native plugin will automatically look for this and use it to style the UI.
