### ISSUE TITLE
documentation link is broken

### ISSUE THREAD

**Issue by softBarbarian** [apptentive/apptentive-cordova#3]

**Comment by skykelsey** [comment]
Can you please let me know which link is broken? I'll get it fixed for you.

**Comment by softBarbarian** [comment]
sorry for not going into any details. the link in your README.md points to this address https://www.apptentive.com/docs/cordova/integration/ which is giving me 404

**Comment by skykelsey** [comment]
OK thank you. We are having some caching issues on our website, which is why this appeared to work for me. You can see the document on github here until we git it fixed. 

https://github.com/apptentive/apptentive-documentation/blob/master/using_apptentive/cordova/integration.md

**Comment by skykelsey** [comment]
OK, the docs are back up. Please let me know if you see this again.
