### ISSUE TITLE
Apptentive.engage deprecation notice

### ISSUE THREAD

**Issue by stevecarlton** [apptentive/apptentive-cordova#5]
When trigger an appetitive event with Apptentive.engage('Ionic - User viewed guest list'); we receive a deprecation notice:

```The old format of this exec call has been removed (deprecated since 2.1). Change to: cordova.exec(null, null, "", "Ionic - User viewed guest list",[null,"ApptentiveBridge","execute",["engage",null]]);```

What could be causing this?

**Comment by jakebarnett** [comment]
Hi Steve,

The format for the using the Apptentive.engage method has been updated, it looks like you are using the old format.  The method is now:

Apptentive.engage(successCallback, errorCallback, 'myEventName', customData);

There is more info here in our docs:

http://www.apptentive.com/docs/cordova/integration/ .

Thanks,
Jake
