### ISSUE TITLE
missing android support-v4

### ISSUE THREAD

**Issue by benconnito** [apptentive/apptentive-cordova#9]
After the 2.0.0 update the maven framework link doesn't seem to work. I get an error on clean/build about missing android-v4, appcomapt, and cardview libs. The maven repo for com.android.support:support-v4 does not exist

**Comment by lastcelebration** [comment]
I have the same problem.

<pre><code>
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_armv7DebugCompile'.
   > Could not find com.android.support:support-v4:23.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.pom
         https://repo1.maven.org/maven2/com/android/support/support-v4/23.0.1/support-v4-23.0.1.jar
     Required by:
         :android:unspecified > com.apptentive:apptentive-android:2.0.1
   > Could not find com.android.support:appcompat-v7:23.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.pom
         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/23.0.1/appcompat-v7-23.0.1.jar
     Required by:
         :android:unspecified > com.apptentive:apptentive-android:2.0.1
   > Could not find com.android.support:cardview-v7:23.0.1.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.0.1/cardview-v7-23.0.1.pom
         https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.0.1/cardview-v7-23.0.1.jar
     Required by:
         :android:unspecified > com.apptentive:apptentive-android:2.0.1
</code></pre>

**Comment by benconnito** [comment]
This is fixed by installing the android support repository. I also have the android support library installed. Using android sdk manager.

**Comment by benconnito** [comment]
after using the android support repo, I now get an error that I need to compile against android sdk 23. the support library required is 23 for the appentive sdk. Unfortunatley cordova doesnt seem to support v23 yet. Any ideas?

**Comment by skykelsey** [comment]
Hello Ben,

Sorry you're having trouble with the integration. Cordova doesn't default to API 23 yet, but you can still target it by modifying the generated `project.properties`. It's an easy process, and would only need to be repeated if you remove and re-add the Android platform to your Cordova app. Our integration docs mention it [here](https://www.apptentive.com/docs/cordova/integration/#supported-platforms), in the paragraph that starts with "Note: Our SDK requires you to compile against Android API level 23.".

Please let me know if you have any trouble with that approach. Hopefully Cordova will let you target API 23 by default soon.
